"""empty message

Revision ID: 14812568a63c
Revises: b7f7ce35545e
Create Date: 2020-11-17 19:21:39.289053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14812568a63c'
down_revision = 'b7f7ce35545e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stations', 'city',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stations', 'city',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
